extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: ${STRAPI_API_URL}/graphql
      headers:
        user-agent: JS GraphQL
        Authorization: Bearer ${STRAPI_API_KEY}
      introspect: false
